_format_version: '1.1'

services:
    # ---------------------------------------------------------------
    # Auth (GoTrue)
    # ---------------------------------------------------------------
    - name: auth-v1
      url: http://auth:9999/
      routes:
          - name: auth-v1-route
            strip_path: true
            paths:
                - /auth/v1/
      plugins:
          - name: cors
          - name: key-auth
            config:
                hide_credentials: false
          - name: acl
            config:
                hide_groups_header: true
                allow:
                    - admin
                    - anon

    # ---------------------------------------------------------------
    # REST (PostgREST)
    # ---------------------------------------------------------------
    - name: rest-v1
      url: http://rest:3000/
      routes:
          - name: rest-v1-route
            strip_path: true
            paths:
                - /rest/v1/
      plugins:
          - name: cors
          - name: key-auth
            config:
                hide_credentials: false
          - name: acl
            config:
                hide_groups_header: true
                allow:
                    - admin
                    - anon

    # ---------------------------------------------------------------
    # Realtime
    # ---------------------------------------------------------------
    - name: realtime-v1
      url: http://realtime:4000/socket/
      routes:
          - name: realtime-v1-route
            strip_path: true
            paths:
                - /realtime/v1/
      plugins:
          - name: cors
          - name: key-auth
            config:
                hide_credentials: false
          - name: acl
            config:
                hide_groups_header: true
                allow:
                    - admin
                    - anon

    # ---------------------------------------------------------------
    # Storage
    # ---------------------------------------------------------------
    - name: storage-v1
      url: http://storage:5000/
      routes:
          - name: storage-v1-route
            strip_path: true
            paths:
                - /storage/v1/
      plugins:
          - name: cors
          - name: key-auth
            config:
                hide_credentials: false
          - name: acl
            config:
                hide_groups_header: true
                allow:
                    - admin
                    - anon

consumers:
    - username: anon
      keyauth_credentials:
          - key: ${ANON_KEY}
      acls:
          - group: anon
    - username: service_role
      keyauth_credentials:
          - key: ${SERVICE_ROLE_KEY}
      acls:
          - group: admin
